# Generated by Django 5.1.4 on 2024-12-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0003_remove_booking_paid_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='booking',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
