# Generated by Django 5.1.4 on 2024-12-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0004_remove_booking_timeslot_booking_visit_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museum',
            name='closing_date',
        ),
        migrations.RemoveField(
            model_name='museum',
            name='opening_hour',
        ),
        migrations.AddField(
            model_name='museum',
            name='closing_dates',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
