# Generated by Django 5.1.4 on 2024-12-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0006_rename_time_end_museum_closing_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='museum',
            old_name='closing_dates',
            new_name='closing_days',
        ),
    ]
