# Generated by Django 5.1.4 on 2024-12-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0007_rename_closing_dates_museum_closing_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='visit_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
