# Generated by Django 5.1.4 on 2024-12-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0008_remove_booking_visit_time_booking_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
    ]
